# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Error_Usuario_Inexistente.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(295, 137)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 90, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 10, 176, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Error = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Error.setContentsMargins(0, 0, 0, 0)
        self.Error.setObjectName("Error")
        self.Error_Usuario_Inexistente = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Error_Usuario_Inexistente.setObjectName("Error_Usuario_Inexistente")
        self.Error.addWidget(self.Error_Usuario_Inexistente, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Aceptar"))
        self.Error_Usuario_Inexistente.setText(_translate("Dialog", "Error: Usuario Inexistente"))
