# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class mainlogin (object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 460, 144, 88))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Made_by = QtWidgets.QLabel(self.layoutWidget)
        self.Made_by.setObjectName("Made_by")
        self.gridLayout_3.addWidget(self.Made_by, 0, 0, 1, 1)
        self.Francisco_Bryndum = QtWidgets.QLabel(self.layoutWidget)
        self.Francisco_Bryndum.setObjectName("Francisco_Bryndum")
        self.gridLayout_3.addWidget(self.Francisco_Bryndum, 1, 0, 1, 1)
        self.Gerardo_Urdaneta = QtWidgets.QLabel(self.layoutWidget)
        self.Gerardo_Urdaneta.setObjectName("Gerardo_Urdaneta")
        self.gridLayout_3.addWidget(self.Gerardo_Urdaneta, 2, 0, 1, 1)
        self.UTN_e_Learning_2021 = QtWidgets.QLabel(self.layoutWidget)
        self.UTN_e_Learning_2021.setObjectName("UTN_e_Learning_2021")
        self.gridLayout_3.addWidget(self.UTN_e_Learning_2021, 3, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(110, 190, 217, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Entry_Password = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Entry_Password.setObjectName("Entry_Password")
        self.gridLayout.addWidget(self.Entry_Password, 1, 1, 1, 1)
        self.Texto_Password = QtWidgets.QLabel(self.layoutWidget1)
        self.Texto_Password.setObjectName("Texto_Password")
        self.gridLayout.addWidget(self.Texto_Password, 1, 0, 1, 1)
        self.Texto_Usuario = QtWidgets.QLabel(self.layoutWidget1)
        self.Texto_Usuario.setObjectName("Texto_Usuario")
        self.gridLayout.addWidget(self.Texto_Usuario, 0, 0, 1, 1)
        self.Entry_Usuario = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Entry_Usuario.setObjectName("Entry_Usuario")
        self.gridLayout.addWidget(self.Entry_Usuario, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.Boton_Ingresar = QtWidgets.QPushButton(self.layoutWidget1)
        self.Boton_Ingresar.setObjectName("Boton_Ingresar")
        self.gridLayout_2.addWidget(self.Boton_Ingresar, 1, 0, 1, 1)
        self.Boton_Crear = QtWidgets.QPushButton(self.layoutWidget1)
        self.Boton_Crear.setObjectName("Boton_Crear")
        self.gridLayout_2.addWidget(self.Boton_Crear, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Made_by.setText(_translate("MainWindow", "Made by"))
        self.Francisco_Bryndum.setText(_translate("MainWindow", "Francrisco Bryndum"))
        self.Gerardo_Urdaneta.setText(_translate("MainWindow", "Gerardo Urdaneta"))
        self.UTN_e_Learning_2021.setText(_translate("MainWindow", "UTN e Learning 2021"))
        self.Texto_Password.setText(_translate("MainWindow", "Password"))
        self.Texto_Usuario.setText(_translate("MainWindow", "Usuario"))
        self.Boton_Ingresar.setText(_translate("MainWindow", "Ingresar"))
        self.Boton_Crear.setText(_translate("MainWindow", "Crear"))
